run:
  timeout: 5m
  tests: true
  skip-dirs:
    - generated
    - vendor

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: evalgo.org/graphium

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
