[phases.setup]
# Use nixos-unstable to get Go 1.25 support
nixpkgsArchive = "f4b140d5b253f5e2a1ff4e5506edbf8267724bde"
nixPkgs = ["go", "git", "curl"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = [
    "cd models && go generate && cd ..",
    "CGO_ENABLED=0 go build -ldflags '-X main.Version=${VERSION:-dev} -w -s' -o graphium evalgo.org/graphium/cmd/graphium"
]

[start]
cmd = "./graphium server"

[variables]
GO111MODULE = "on"
CGO_ENABLED = "0"
CG_SERVER_PORT = "8080"
