server:
  host: 0.0.0.0
  port: 8095
  debug: false

  # TLS/HTTPS configuration
  tls_enabled: false  # Set to true to enable HTTPS
  tls_cert: /path/to/cert.pem
  tls_key: /path/to/key.pem

  # Timeouts
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 10s

couchdb:
  url: http://localhost:5985
  database: graphium
  username: admin
  password: testpass

agent:
  api_url: http://localhost:8095
  host_id: localhost-docker
  datacenter: local
  docker_socket: /var/run/docker.sock
  sync_interval: 30s

security:
  # Authentication settings
  auth_enabled: true  # Set to true to enable JWT authentication
  jwt_secret: change-me-in-production-use-a-secure-random-string
  jwt_expiration: 24h
  refresh_token_expiration: 168h  # 7 days

  # Agent authentication
  agent_token_secret: change-me-in-production-use-different-secret-for-agents

  # API Keys (for service-to-service authentication)
  # Generate with: openssl rand -base64 32
  api_keys: []
    # - "sk_prod_abc123..."
    # - "sk_test_xyz789..."

  # Rate limiting (requests per second, 0 = disabled)
  rate_limit: 100

  # CORS settings (empty = disabled)
  allowed_origins:
    - http://localhost:3000
    - http://localhost:8095

logging:
  level: info
  format: json
  output: stdout
