server:
  host: 0.0.0.0
  port: 8095
  debug: false

couchdb:
  url: http://localhost:5985
  database: graphium
  username: admin
  password: testpass

agent:
  api_url: http://localhost:8095
  host_id: localhost-docker
  datacenter: local
  docker_socket: /var/run/docker.sock
  sync_interval: 30s

security:
  # Authentication settings
  auth_enabled: false  # Set to true to enable JWT authentication
  jwt_secret: change-me-in-production-use-a-secure-random-string
  jwt_expiration: 24h
  refresh_token_expiration: 168h  # 7 days

  # Rate limiting (requests per second, 0 = disabled)
  rate_limit: 100

  # CORS settings (empty = disabled)
  allowed_origins:
    - http://localhost:3000
    - http://localhost:8095

logging:
  level: info
  format: json
  output: stdout
